### ISSUE TITLE
Move this repo out of the stylelint org

### ISSUE THREAD

**Issue by jeddy3** [ntwb/stylelint-config-wordpress#20]
@ntwb We're freeing up the stylelint org to focus on stylelint as a tool rather than the configs. As such we are moving the SuitCSS, Wordpress, CSS Recipes and Standard configs out of the org. We've [just finished](https://github.com/suitcss/stylelint-config-suitcss/issues/5) transferring the SuitCSS config to the SuitCSS org. Would we able to transfer this repo to your github user and then you can decided where best to put it after that (be it the WordPress org or else where)?

**Comment by ntwb** [comment]
Yeah sure, transfer it to mine for now and I'll speak to some folks about moving it elsewhere.

**Comment by ntwb** [comment]
Based on the comment here https://github.com/suitcss/stylelint-config-suitcss/issues/5#issuecomment-179954323 and admin rights etc to transfer the repo, as I had admin access I've transferred it to my user account :)

**Comment by jeddy3** [comment]
Fantastic :)

Thank you!

**Comment by ntwb** [comment]
Thank me? Thank YOU :smile:
