### ISSUE TITLE
List compatible stylelint versions as a peerDependency

### ISSUE THREAD

**Issue by Arcanemagus** [ntwb/stylelint-config-wordpress#38]
Can you add the compatible versions of `stylelint` as a `peerDependency` in the package.json? This will make it obvious which versions of `stylelint` this will work with.

**Comment by ntwb** [comment]
Fixed via https://github.com/ntwb/stylelint-config-wordpress/commit/46027b9f6c96fed189999f3cdcb66e070436a2e6
