### ISSUE TITLE
Update rules

### ISSUE THREAD

**Issue by jahvi** [ntwb/stylelint-config-wordpress#45]
It'd be worth updating the rules with the latest patch in the WP core css lint discussion:

https://core.trac.wordpress.org/attachment/ticket/29792/29792.3.diff

Can submit PR if interested.

**Comment by ntwb** [comment]
Thanks, that patch is in fact the last patch that I uploaded to that ticket, the rules as they stand in this repo are more up to date and current than that patch, I'll update the patch in that ticket and refresh the patch soon.

**Comment by jahvi** [comment]
Oh didn't know that was you, good to know

**Comment by ntwb** [comment]
Yup, wasn't lucky enough to get the `netweb` username here on GitHub so I'm @ntwb on GitHub
